apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmix-app
  namespace: kl3init-dev
  labels:
    app: jmix-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmix-app

  template:
    metadata:
      labels:
        app: jmix-app

    spec:
      serviceAccountName: hazelcast-sa

      containers:
        - name: jmix-app
          image: docker.io/kl3init/jmix-k8s:1.0.7
          imagePullPolicy: Always
          volumeMounts:
            - name: liquibase-changelog
              mountPath: /config/liquibase/changelog.xml
              subPath: changelog.xml
            - name: liquibase-changelog-files
              mountPath: /config/liquibase/changelog
              readOnly: true

          ports:
            - containerPort: 8080
            - containerPort: 5701

          envFrom:
            - configMapRef:
                name: jmix-secret
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]

      volumes:
        - name: liquibase-changelog
          configMap:
            name: jmix-liquibase-changelog
        - name: liquibase-changelog-files
          configMap:
            name: jmix-liquibase-changelog-files