apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmix-k8s
  namespace: kl3init-dev
  labels:
    app: jmix-k8s

spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmix-k8s

  template:
    metadata:
      labels:
        app: jmix-k8s

    spec:
      serviceAccountName: hazelcast-sa

      containers:
        - name: jmix-k8s
          image: docker.io/kl3init/jmix-k8s:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: MAIN_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: jmix-secret
                  key: MAIN_DATASOURCE_URL

            - name: MAIN_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: jmix-secret
                  key: MAIN_DATASOURCE_USERNAME

            - name: MAIN_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: jmix-secret
                  key: MAIN_DATASOURCE_PASSWORD

            - name: SPRING_PROFILES_ACTIVE
              value: k8s

            - name: HZ_NETWORK_JOIN_KUBERNETES_ENABLED
              value: "true"
