apiVersion: v1
kind: ConfigMap
metadata:
  name: jmix-config
  namespace: kl3init-dev

data:
  MAIN_DATASOURCE_URL: jdbc:postgresql://your-db:5432/yourdb
  MAIN_DATASOURCE_USERNAME: youruser
  MAIN_DATASOURCE_PASSWORD: yourpassword
  JMIX_LIQUIBASE_ENABLED: "true"
  SPRING_PROFILES_ACTIVE: k8s
  HZ_NETWORK_JOIN_KUBERNETES_ENABLED: "true"