apiVersion: v1
kind: ConfigMap
metadata:
  name: jmix-config
  namespace: kl3init-dev

data:
  MAIN_DATASOURCE_URL: jdbc:postgresql://27.118.20.16/jmix-k8s?currentSchema=dev
  MAIN_DATASOURCE_USERNAME: postgres
  MAIN_DATASOURCE_PASSWORD: Abcd@1234
  JMIX_LIQUIBASE_ENABLED: "true"
  SPRING_PROFILES_ACTIVE: k8s
  HZ_NETWORK_JOIN_KUBERNETES_ENABLED: "true"