apiVersion: v1
kind: ConfigMap
metadata:
  name: jmix-secret
  namespace: kl3init-dev
data:
  MAIN_DATASOURCE_URL: "jdbc:postgresql://27.118.20.16:5432/jmix-k8s?currentSchema=jmix-k8s"
  MAIN_DATASOURCE_USERNAME: "postgres"
  MAIN_DATASOURCE_PASSWORD: "Abcd@1234"